# Generated by Django 4.0.4 on 2022-07-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_emp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=100)),
                ('area_tra', models.CharField(max_length=100)),
                ('cap_maq', models.BooleanField(verbose_name=False)),
                ('cap_grua', models.BooleanField(verbose_name=False)),
                ('cap_alt', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
