# Generated by Django 4.0.4 on 2022-07-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_empleado_url_emp_alter_empleado_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='url_emp',
            field=models.CharField(default='', max_length=300),
        ),
    ]
