# Generated by Django 4.0.4 on 2022-07-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0004_alter_empleado_url_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='area_tra',
            new_name='area_de_trabajo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='cap_alt',
            new_name='curso_altura',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='cap_grua',
            new_name='curso_grua',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='cap_maq',
            new_name='curso_maquinaria',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='nom_emp',
            new_name='nombre_completo',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='rut_emp',
            new_name='rut',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='url_emp',
            new_name='url_empleado',
        ),
    ]
