# Generated by Django 4.0.4 on 2022-07-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0006_alter_empleado_url_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='url_empleado',
            field=models.CharField(default='http://emiliosk11.pythonanywhere.com/empleado/<django.db.models.fields.CharField>/?format=json', max_length=300),
        ),
    ]
