# Generated by Django 4.0.4 on 2022-07-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0008_alter_empleado_url_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen_empleado',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='url_empleado',
            field=models.CharField(default='http://emiliosk11.pythonanywhere.com/empleado/rut/?format=json', max_length=300),
        ),
    ]
